### ISSUE TITLE
Tests fail with Mojolicious 7

### ISSUE THREAD

**Issue by eserte** [zoffixznet/HTML-ExtractText#13]
My smokers started to report failures, probably only if Mojolicious 7 is installed. Sample report: http://www.cpantesters.org/cpan/report/f4e62f22-4e01-11e6-babd-99c5dbe93021

**Comment by eserte** [comment]
Probably relevant change: https://metacpan.org/source/SRI/Mojolicious-7.0/Changes#L8

**Comment by zoffixznet** [comment]
Fixed.
